### PR TITLE
Fixing media migration issues

### PR DESCRIPTION
**Pull request by rmarsh1ua**
We found a problem in the media_migration module that doesn't properly translate  tags to media
tags so this commit fixes that issue for our specific use case by extending and re-implementing some
code that's available in the media_migration module. The other noteable changes:
 - Re-using the media_migration code necessitated adding service injection to this module.
 - There were a lot of problems with some inconsistencies that popped up when we changed the name of
 this module, i.e. not everything from that had been properly cleaned up. A bunch of files have been
 renamed or had small changes to make the module name consistently be represented as grad_migration.

### CODE REVIEW

**Review by pbarabe — APPROVED** [review]
@rmarsh1ua Looks good to me. Do you need me to give these changes a test run?

**Comment by rmarsh1ua** [comment]
Hold up on this. I want to update the README tomorrow and then have you test stuff.

**Comment by rmarsh1ua** [comment]
Okay Patrick, the README has been updated so now would be a better time to try and test/review this.

**Comment by pbarabe** [comment]
@rmarsh1ua I committed `drupal:migrate_devel` as a dependency in `grad_migration.info.yml`.

I'm a little unsure of some of what I'm seeing on a test run of the PC/Coverdell site (see my comments in our D9 Migrations teams chat).

**Pull request merged**
